apiVersion: v1
kind: Service
metadata:
  name: springcheerz
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springcheerz
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcheerz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springcheerz
  template:
    metadata:
      labels:
        app: springcheerz
    spec:
      containers:
        - name: springcheerz
          image: springcheerz:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"