ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

database:
  url: jdbc:postgresql://postgres-ktorkustom:5432/ktorkustom
  driver: org.postgresql.Driver
  user: ktorkustom
  password: ktorkustom_pass

rabbitmq:
  uri: amqp://guest:guest@rabbitmq:5672
  connection:
    name: default_connection
    attempts: 20
    attemptDelay: 10
  dispatcher:
    threadPoolSize: 4
  tls:
    enabled: false